packages/synthchron-tauri/package.json, packages/synthchron-tauri/src/main.tsx, yarn.lock
Adding MateriUI and Fonts to the project
=> Syn 86/add material UI

packages/synthchron-tauri/package.json, packages/synthchron-tauri/src/components/Debug.tsx, yarn.lock
Adds an example of how to check for online/offline. Useful for sharing later
=> add online/offline check

packages/synthchron-tauri/src/Types/project.ts
Added a simple data structure for project, still need to be exported to be used with the cards and implement it into a persistent state manager.
=> Added a simple Project datastructure

packages/synthchron-tauri/src/components/ProjectCard.tsx
Only changes the time field to a "last updated {time}" format
=> update 'last edited' field

packages/synthchron-tauri/src/components/common/persistentStore.ts, packages/synthchron-tauri/src/components/react-flow/leftSidebar/ProjectTab.tsx
- Adds a project name field to left drawer
- Adds a project description field to left drawer
=> Syn 111 implement editing project information name and description

packages/synthchron-simulator/src/model-examples/petriNetExamples.ts, packages/synthchron-simulator/src/process-engines/petrinet-engine.ts, packages/synthchron-simulator/src/simulation.ts, packages/synthchron-simulator/src/types/general.ts, packages/synthchron-simulator/src/types/processModelTypes/petriNetTypes.ts, packages/synthchron-simulator/test/index.spec.ts, packages/synthchron-tauri/src/components/NewProjectModal.tsx, packages/synthchron-tauri/src/components/flowTransformer.ts, packages/synthchron-tauri/src/components/react-flow/DrawerWrapper.tsx, packages/synthchron-tauri/src/components/react-flow/RightSidebar.tsx, packages/synthchron-tauri/src/components/react-flow/leftSidebar/CollaborationTab.tsx, packages/synthchron-tauri/src/components/react-flow/processModels/petriNet/customNodes/PlaceNode.tsx, packages/synthchron-tauri/src/components/react-flow/processModels/petriNet/petriNetFlowConfig.ts, packages/synthchron-tauri/src/components/react-flow/processModels/processModelFlowConfig.ts, packages/synthchron-tauri/src/components/react-flow/rightSidebar/GeneralTab.tsx, packages/synthchron-tauri/src/components/react-flow/rightSidebar/SimulationTab.tsx, packages/synthchron-tauri/src/components/react-flow/ydoc/flowStore.ts, packages/synthchron-tauri/src/pages/EditorPage.tsx
- Add a simulation tab on the right
- Add a general settings tab on the right
- Add a petri-net specific interface for adding acceptance expressions
- Add a type in the simulator for returning the reason for accepting a state
- Update tests to match new interface
- Update simulator to use the global instead of local expressions
=> Syn 128 add accepting state window

.github/workflows/auto_dependabot.yaml
=> add auto dependabot approve workflow

.github/workflows/auto_dependabot.yaml
Adds an if clause to only run the action on dependabot prs, it works otherwise but this is prettier
=> add clause to only run on dependabot prs

netlify.toml
This PR makes netlify ignore dependabot updates, as those are about to fill our free netlify quota
=> add ignore clause to build

packages/synthchron-tauri/src/components/NewProjectModal.tsx
Adds a simple petri net as default option
=> add default petri net model

.github/workflows/auto_dependabot.yaml
Adds necessary permissions to auto dependabot action as described in https://github.com/cli/cli/discussions/6379
=> add permissions to auto_dependabot action

packages/synthchron-simulator/src/simulation.ts, packages/synthchron-simulator/src/types/general.ts, packages/synthchron-simulator/test/index.spec.ts, packages/synthchron-tauri/src/components/editor/rightSidebar/SimulationTab.tsx
Add probabilistic termination in Accepting state, changed tests a bit and a bit of code reordering
=> Add probabilistic termination at accepting state

packages/synthchron-simulator/src/process-engines/petrinet-engine.ts, yarn.lock
Fixed negative weight bug, and also adding tokens to the target bug
=> Fix Negative Weights and Adding weights to target

packages/synthchron-tauri/src/Routing.tsx
=> fix collaboration tab

packages/synthchron-tauri/src/components/editor/SidebarsWrapper.tsx
Added ability to scroll the sidebars
=> Add overflow to sidebar panes

packages/synthchron-simulator/src/process-engines/petrinet-engine.ts, packages/synthchron-simulator/src/simulation.ts, packages/synthchron-simulator/src/types/simulationTypes.ts, turbo.json
- Removes the redundant ActivityType generic 
- Fixed the deprecation issue with turborepo
=> Just a bit of refactoring

packages/synthchron-tauri/src/components/editor/StateFlow.tsx
Fixed incorrect cursor placement
=> fix collab cursor placement

packages/synthchron-postprocessor/src/insert.ts, packages/synthchron-tauri/src/Routing.tsx, packages/synthchron-tauri/src/components/CustomAppBar.tsx, packages/synthchron-tauri/src/components/PostProcessing.tsx
To reviewer, I have made a user interface to test the post processing. This is not intended to be the actual interface and should be removed, but it is kept, as it makes testing easy. To test open the application and go to the postprocessing tab.
- Made post processing method 'insert'
- For insertion I have created 3 different methods, insert a duplicate, insert an event which exists in the log and insert a custom event.
=> Syn 175 post proc insert

.github/workflows/publish.yaml
Create a new environment for each PR
=> Syn 184 readd publish to netlify

packages/synthchron-tauri/src/components/CustomAppBar.tsx, packages/synthchron-tauri/src/components/editor/leftSidebar/CollaborationTab.tsx, packages/synthchron-tauri/src/components/editor/leftSidebar/ProjectTab.tsx
Fixed issue with random room code not being shown
Fixed issue with room code persisting
Fixed issue with not being able to change room code after trying to connect to a room that already exists
=> Syn 174 and 180 room code fixes

packages/synthchron-simulator/src/simulation.ts
Make simulation traces random without random seed and all deterministic with a seed
=> Make traces random and deterministic with seed

packages/synthchron-tauri/package.json, packages/synthchron-tauri/src/Routing.tsx, packages/synthchron-tauri/src/components/CustomAppBar.tsx, packages/synthchron-tauri/src/components/swarm/CheckedList.tsx, packages/synthchron-tauri/src/components/swarm/TitledCheckedList.tsx, packages/synthchron-tauri/src/pages/SwarmPage.tsx, yarn.lock
Adds a tab that allows swarm generation of traces.
Adds a dependency to jszip since we need to generate zip files.
=> add swarm generation page

packages/synthchron-simulator/src/model-examples/petriNetExamples.ts, packages/synthchron-simulator/src/simulation.ts, packages/synthchron-simulator/test/index.spec.ts
Added Stopping conditional to not depend on progress, wrote more tests
=> SYN-191-Mass-trace-generation-fix-simulation-termination

packages/synthchron-tauri/package.json, packages/synthchron-tauri/src/components/NewProjectDefault.tsx, packages/synthchron-tauri/src/components/NewProjectFile.tsx, packages/synthchron-tauri/src/components/NewProjectModal.tsx, yarn.lock
Added another view to create project, to use files as the project instead of creating a default project.
Might be some boilerplate, that can be worked into a combined repository, but didnt see it too necesarry, but do tell, if its something i should be taking care of.
- [ X ] I have performed a self-review of my code
=> Syn 49 implement import model function

packages/synthchron-tauri/src/pages/SwarmPage.tsx, yarn.lock
=> swarm simulation with no configs or projects fixed

packages/synthchron-tauri/src/pages/PostProcessingPage.tsx
Updated the UI of postprocessing page
Allowed uploading multiple .xes files at a time
Allowed uploading .zip files
Changed 'generate xes' button to postprocess all files, and zip them if there are multiple.
Not that clear, but singular files can be removed by clicking them.
=> Syn 204 batch postprocessing

packages/synthchron-tauri/src/components/CustomAppBar.tsx
Comment out debug pages from the app bar
- [Yes] I have performed a self-review of my code
=> Feat routing remove debug pages
